services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASEUSER}
      - POSTGRES_DB=${DATABASENAME}
      - POSTGRES_PASSWORD=${DATABASEPASSWORD}
  # api:
  #   image: api
  #   build: ./api
  #   container_name: api
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - ./api:/api
  #   environment:
  #     - DBHOST=db # database hostname/IP address
  #     - APIPORTI=5010
  #   ports:
  #     - ${APIPORTI}:${APIPORTI}
  # ui:
  #   image: ui
  #   build: ./ui
  #   container_name: ui
  #   depends_on:
  #     - api
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - ./ui:/ui
  #   environment:
  #     - UIPORTI=5011
  #   ports:
  #     - ${UIPORTI}:${UIPORTI}
